import type { NextPage } from 'next'
import Head from 'next/head'
import {useState} from 'react'
import Button from './button'

export type myType = {
  url:string, 
  text:string
}

const Home: NextPage = () => {
   
  const [urls, ] = useState([
    {url: "https://github.com/Remisys/", text: "Github"}, 
    {url: "https://www.linkedin.com/in/yosef-ian-k-b944411a1/", text: "Linkedin"},
    {url: "https://www.xing.com/profile/YosefIan_Kurniadi/cv", text: "Xing"},
  ]); 
  return (
    <div className=" min-h-screen  flex flex-col items-center bg-gradient-to-r from-yellow-300 to-rose-300" >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className=" sticky top-0   flex flex-row justify-center items-center sm:p-[60px] p-10  w-full text-center bg-white z-50">
        <h1 className=" text-blue-500 sm:text-6xl text-4xl">Yosef Ian</h1>
      </header>
      <nav className="flex flex-row justify-center items-center w-full  grow ">
        <div className="flex flex-row  justify-center  items-center flex-wrap  md:w-[100%]  w-[50%] h-[50%] ">
          {urls.map( (x) => (<Button url={x.url} text={x.text} />))}
        </div>

      </nav>
      <main className="flex flex-col ">

      

      </main>

      <footer className="w-full bg-inherit">
          <svg className="" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 800 100" 
             style={{transform: "scale(1,-1)"}}>

          <linearGradient  id="a">
        <stop offset="0%" stopColor="#a855f7" />
       
        <stop offset="50%" stopColor="#3b82f6" />
       
        <stop offset="100%" stopColor="#0ea5e9" />
        
            </linearGradient> 
              {/**<rect width="100%" height="100%" fill="red" /> */}
              <path  d={"M 0,0 v 50  q 200,50 400,0 q 200,-50 400,0  v -50 h -800"} fill="url(#a)" ></path>

              {/**<text x="150" y="125" font-size="60" text-anchor="middle" fill="white">SVG</text>*/}
              </svg>
              <div className="m-0 w-full bg-gradient-to-r from-purple-500 via-blue-500  to-sky-500 translate-y-[-1px] flex flex-row  ">
                <h1 className="p-12 sm:text-4xl text-3xl translate-y-[-10%] text-white lg:p-7 hover:underline-offset-[12px] hover:underline">
                  <a href="mailto:yosef.ian.kurniadi@stud.uni-hannover.de?subject=Hi Yosef">Contact Me</a> 
                </h1>
              </div>
              
     
      </footer>
      
    </div>
  )
}

export default Home


