import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'



const Home: NextPage = () => {
  return (
    <div className=" min-h-screen h-screen flex flex-col items-center " >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className=" sticky top-0   flex flex-row justify-center items-center lg:p-[60px] p-10  w-full text-center bg-white z-50">
        <h1 className=" text-blue-500 lg:text-6xl text-4xl"> Yosef Ian</h1>
      </header>
      <nav className="flex flex-row justify-center items-center w-full grow  bg-gradient-to-r from-yellow-300 to-rose-300">
        <div className="flex flex-row justify-center flex-wrap xl:max-w-xl md:w-[70%] max-w-lg  bg-inherit w-[50%]">
          
          <div className="backdrop-blur-[72px] bg-white/[.4] shadow-md  flex-1 border-2 md:m-10 m-5  border-slate-400 hover:border-purple-700 rounded-lg text-center ">
            <p className="lg:text-2xl text-xl  md:p-10 p-5 font-medium text-purple-600 hover:underline decoration-[3px] underline-offset-[0.5rem]">Github</p>
          </div>
          <div className="backdrop-blur-[72px] bg-white/[.4] shadow-md flex-1  border-2 md:m-10 m-5  border-slate-400 hover:border-purple-700 rounded-lg text-center">
            <p className="lg:text-2xl  text-xl md:p-10  p-5 font-medium text-purple-600 hover:underline decoration-[3px] underline-offset-[0.5rem]">Linkedin</p>
          </div>
          <div className="backdrop-blur-[72px] bg-white/[.4] shadow-md  flex-1 border-2 md:m-10 m-5  border-slate-400 hover:border-purple-700 rounded-lg text-center ">
            <p className="lg:text-2xl text-xl  md:p-10 p-5 font-medium text-purple-600 hover:underline decoration-[3px] underline-offset-[0.5rem]">Xing</p>
          </div>
   
        </div>

      </nav>
      <main className="flex flex-col ">

      

      </main>

      <footer className="  bg-slate-800 w-full flex flex-row justify-center">
          <h1 className="lg:text-4xl text-2xl text-white lg:p-20 p-10 ">Contact Me</h1>
      </footer>
    </div>
  )
}

export default Home

